source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JZRecorder_Example', :exclusive => true do
  pod "JZRecorder", :path => "../"
end

target 'JZRecorder_Tests', :exclusive => true do
  pod "JZRecorder", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
